baseURL = "https://blog.devjugal.com/"
languageCode = "en-us"
title = "Jugal Kishore"
theme = "hello-friend-ng"
googleAnalytics = "UA-167086893-1"

[params]
    author = "Jugal Kishore"
    homeSubtitle = "Setting up base camp on Mars! 📡"
    dateform        = "Jan 2, 2006"
    dateformShort   = "Jan 2"
    dateformNum     = "2006-01-02"
    dateformNumTime = "2006-01-02 15:04 -0700"
    contentTypeName = "posts"
    defaultTheme = "dark"
    [params.logo]
        logoText     = "$ crazyuploader"
        logoHomeLink = "https://blog.devjugal.com/"
[languages]
    [languages.en]
        subtitle  = ""
        weight    = 1
        copyright = 'Junglee Labs'
[menu]
    [[menu.main]]
        name   = "TIL"
        weight = 5
        url    = "https://til.devjugal.com"
    [[menu.main]]
        name   = "contact"
        weight = 4
        url    = "/contact"
    [[menu.main]]
        name   = "posts"
        weight = 3
        url    = "/posts"
    [[menu.main]]
        name   = "about me"
        weight = 1
        url    = "/about"
    [[menu.main]]
        name   = "school project"
        weight = 2
        url    = "https://school.devjugal.com"
[[params.social]]
    name = "github"
    url  = "https://out.devjugal.com/github"
[[params.social]]
    name = "docker"
    url  = "https://out.devjugal.com/dockerhub"
[[params.social]]
    name = "dev"
    url  = "https://out.devjugal.com/devto"
[[params.social]]
    name = "linkedin"
    url  = "https://out.devjugal.com/linkedin"
[[params.social]]
    name = "facebook"
    url  = "https://out.devjugal.com/facebook"
[[params.social]]
    name = "twitter"
    url  = "https://out.devjugal.com/twitter"
[[params.social]]
    name = "telegram"
    url  = "https://out.devjugal.com/telegram"
