baseURL = "https://jugalkishore.me/"
languageCode = "en-us"
title = "Jugal Kishore"
theme = "modified-hugo-theme"
googleAnalytics = "UA-167086893-1"

[params]
    author = "Jugal Kishore"
    homeSubtitle = "Setting up base camp on Mars! 📡"
    dateform        = "Jan 2, 2006"
    dateformShort   = "Jan 2"
    dateformNum     = "2006-01-02"
    dateformNumTime = "2006-01-02 15:04 -0700"
    contentTypeName = "posts"
    defaultTheme = "dark"
    [params.logo]
        logoText     = "$ crazyuploader"
        logoHomeLink = "https://jugalkishore.me/"
[languages]
    [languages.en]
        subtitle  = ""
        weight    = 1
        copyright = 'Junglee Labs'
[menu]
    [[menu.main]]
        name   = "contact"
        weight = 4
        url    = "/contact"
    [[menu.main]]
        name   = "posts"
        weight = 3
        url    = "/posts"
    [[menu.main]]
        name   = "about me"
        weight = 1
        url    = "/about"
    [[menu.main]]
        name   = "school project"
        weight = 2
        url    = "/school"
[[params.social]]
    name = "github"
    url  = "https://github.com/crazyuploader"
[[params.social]]
    name = "docker"
    url  = "https://hub.docker.com/u/crazyuploader"
[[params.social]]
    name = "devto"
    url  = "https://dev.to/crazyuploader"
[[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/crazyuploader/"
[[params.social]]
    name = "facebook"
    url  = "https://facebook.com/profile.php?id=100051213879144"
[[params.social]]
    name = "instagram"
    url  = "https://instagram.com/crazyjugal"
[[params.social]]
    name = "twitter"
    url  = "https://twitter.com/crazyjugal"
[[params.social]]
    name = "telegram"
    url  = "https://t.me/crazyuploader"
